In [2]:
!mpiexec -n 6 ~/anaconda3/bin/python gather-simple.py

<class 'list'>
[[67, -89, 0, 0], [68, -88, 90, 1], [69, -87, 180, 2], [70, -86, 270, 3], [71, -85, 360, 4], [72, -84, 450, 5]]


In [4]:
!mpiexec -n 6 ~/anaconda3/bin/python gathernumpy.py

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]]


In [5]:
!mpiexec -n 6 ~/anaconda3/bin/python allgather.py

rank 5 data :  [0, 1, 2, 3, 4, 5]
rank 3 data :  [0, 1, 2, 3, 4, 5]
rank 2 data :  [0, 1, 2, 3, 4, 5]
rank 4 data :  [0, 1, 2, 3, 4, 5]
rank 0 data :  [0, 1, 2, 3, 4, 5]
rank 1 data :  [0, 1, 2, 3, 4, 5]


In [6]:
!mpiexec -n 4 ~/anaconda3/bin/python alltoall.py

rank 0 recvdata :  [0. 0. 0. 0.]
rank 1 recvdata :  [1. 2. 3. 4.]
rank 3 recvdata :  [ 3.  6.  9. 12.]
rank 2 recvdata :  [2. 4. 6. 8.]
